import test from 'node:test';
import assert from 'node:assert/strict';
import {mediaBox,resolveCollisions,boardConnections} from '../public/board-logic.mjs';
import {manualStructure,SECTIONS,newProject} from '../public/domain.mjs';
import {applyOrganization} from '../organization.mjs';
test('board keeps portrait/landscape aspect and resolves collisions without losing nodes',()=>{for(const [w,h]of [[1920,1080],[1080,1920],[100,100]]){const box=mediaBox({width:w,height:h});assert.ok(Math.abs(box.width/box.height-w/h)<.01);}const r=resolveCollisions(Array.from({length:350},(_,i)=>({id:i,x:0,y:0,w:100,h:100})));assert.equal(r.length,350);for(let i=1;i<r.length;i++)assert.ok(r[i].y>=r[i-1].y+124);});
test('board wires represent real subject source mappings and note inputs',()=>{const p=newProject();p.references=[{id:'r'}];p.subjects=[{id:'s',sources:[{sourceId:'r'},{sourceId:'deleted'}]}];p.board={notes:[{id:'n'}]};const e=boardConnections(p);assert.ok(e.some(([a,b])=>a==='reference:r'&&b==='subject:s'));assert.ok(e.some(([a,b])=>a==='note:n'&&b==='draft'));assert.ok(!JSON.stringify(e).includes('deleted'));});
test('manual structure has all six empty native headings',()=>{assert.equal(manualStructure(),SECTIONS.map(s=>s+':').join('\n\n')+'\n');});
test('organization rejects unknown sources and preserves manual carry',()=>{const p=newProject();p.references=[{id:'r',type:'image',description:'Keep only the color'}];const plan={references:[{reference:'<Picture 1>',tags:['red'],carry:'Everything'}],subjects:[{name:'Background',definition:'Red field',references:['<Picture 1>']}]};const next=applyOrganization(p,JSON.stringify(plan));assert.equal(next.references[0].description,p.references[0].description);assert.equal(next.subjects[0].sources[0].sourceId,'r');assert.equal(p.subjects.length,0);plan.subjects[0].references=['<Picture 99>'];assert.throws(()=>applyOrganization(p,JSON.stringify(plan)),/unavailable/);});
import {Inference} from '../worker.mjs';
import {directionPrompt} from '../direction.mjs';
test('reference observations reuse exact source identity, invalidate trim/model, and honor reinspection',async()=>{class Fixture extends Inference{calls=0;async run(i,c,j){this.calls++;j.output='A red field.';}}const worker=new Fixture('.','.'),ref={id:'r',path:'red.png',width:100,height:100,trimEnd:3},project={references:[ref],directorMessages:[]},input={project,model:'bonsai',projector:'mmproj'},config={profiles:{}};const job={id:'job'};const observed=await worker.observe(input,ref,config,job);await worker.observe(input,ref,config,job);assert.equal(worker.calls,1);const other=new Fixture('.','.');await other.observe({...input,project:{...project,directorMessages:[{observations:[observed]}]}},{id:'r',path:'red.png',width:100,height:100,trimEnd:3},config,job);assert.equal(other.calls,0);await worker.observe(input,{...ref,trimEnd:2},config,job);await worker.observe({...input,model:'other'},ref,config,job);await worker.observe({...input,forceInspect:true},ref,config,job);assert.equal(worker.calls,4);});
test('Director keeps complete long client turns, early decisions and corrections',()=>{const p=newProject();p.directorMessages=[{role:'user',text:'Keep the camera fixed.'},{role:'assistant',text:'Could add rain?'},...Array.from({length:8},(_,i)=>({role:'user',text:'Detail '+i})),{role:'user',text:'Context '.repeat(400)+'FINAL CORRECTION: no music, no rain.'}];const text=directionPrompt(p,'director');assert.match(text,/Keep the camera fixed/);assert.match(text,/FINAL CORRECTION: no music, no rain/);assert.match(text,/Later corrections override/);});

test('automatic assembly uses organizer plus reviewed compilation without redundant specialists',async()=>{class Fixture extends Inference{calls=[];async specialist(i,c,j,kind){this.calls.push(kind);return JSON.stringify({references:[],subjects:[]});}async run(i,c,j){this.calls.push('compile');assert.equal(i.review,true);assert.equal(i.mode,'minimal');j.state='done';}}const worker=new Fixture('.','.');worker.active={cancelled:false};await worker.workflow({action:'assemble',project:newProject(),model:'bonsai'},{profiles:{}},{id:'test'});assert.deepEqual(worker.calls,['organize','compile']);});
