import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

test('local service persists snapshots, isolates destinations, and rejects stale saves',async t=>{
  const dir=await mkdtemp(path.join(os.tmpdir(),'h3-test-'));
  const port=47839,base=`http://127.0.0.1:${port}`;
  const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,H3_PORT:String(port),H3_DATA_DIR:dir},stdio:['ignore','pipe','pipe'],windowsHide:true});
  t.after(()=>child.kill());
  await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',c=>reject(new Error('Server exited '+c)));});
  const status=await(await fetch(base+'/api/status')).json();
  const workflow=await fetch(base+'/api/workflow/Onigiri%20Minimax%20H3');assert.equal(workflow.status,200);assert.ok((await workflow.json()).nodes.length);assert.equal((await fetch(base+'/api/workflow/not-a-workflow')).status,400);
  const send=(route,data,headers={})=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json','X-H3-Token':status.csrf,...headers},body:JSON.stringify(data)});
  const project=await(await send('/api/projects',{})).json();
  assert.deepEqual(await(await fetch(base+'/api/dashboard')).json(),{revision:0,homeFolders:[]});
  const home=await(await send('/api/dashboard',{revision:0,homeFolders:['Short films',' Empty folder ','Short films']})).json();
  assert.deepEqual(home,{revision:1,homeFolders:['Short films','Empty folder'],folders:['Short films','Empty folder']});
  assert.equal((await send('/api/dashboard',{revision:0,homeFolders:[]})).status,409);
  assert.deepEqual(JSON.parse(await readFile(path.join(dir,'dashboard.json'),'utf8')),home);
  assert.equal((await send('/api/dashboard',{revision:1,homeFolders:['bad\nname']})).status,400);
  const unpinned=await(await send('/api/dashboard',{revision:1,homeFolders:[]})).json();
  assert.deepEqual(unpinned.folders,['Short films','Empty folder']);
  assert.deepEqual(unpinned.homeFolders,[]);
  const folderScene=await(await send('/api/projects',{folder:'Empty folder'})).json();assert.equal(folderScene.folder,'Empty folder');
  project.board={positions:{intent:{x:120,y:80}},notes:[{id:'n1',title:'Note',text:'No music.'}],view:{x:24,y:30,zoom:.8}};
  project.prompt='[Shot 1] A quiet room.';project.missingMentions=[{field:'reference:removed-reference',start:0,token:'<Picture 1>'}];
  project.directorMessages=[{id:'message-a',role:'user',text:'Keep the scene quiet.',referenceIds:[]}];project.directorLinks=[];project.directorPlan='A quiet room, static camera.';project.draftText='No music.';project.workflowMode='minimal';
  const responses=await Promise.all([send('/api/project/'+project.id,project),send('/api/project/'+project.id,project)]);
  assert.deepEqual(responses.map(x=>x.status).sort(),[200,409]);
  const saved=await responses.find(x=>x.status===200).json();
  assert.deepEqual(saved.board,project.board);assert.deepEqual(saved.directorMessages,project.directorMessages);assert.equal(saved.directorPlan,project.directorPlan);assert.equal(saved.draftText,'No music.');assert.equal(saved.workflowMode,'minimal');
  const snap=await(await send('/api/snapshots',saved)).json();
  saved.prompt='Changed later';await send('/api/project/'+saved.id,saved);
  assert.equal(JSON.parse(await readFile(snap.path,'utf8')).prompt,project.prompt);
  const a=await(await send('/api/bridge/sessions',{target:'A'},{'X-H3-Bridge':'1'})).json();
  const b=await(await send('/api/bridge/sessions',{target:'B'},{'X-H3-Bridge':'1'})).json();
  await send('/api/bridge/session/'+a.token,{action:'send',snapshot:snap});
  assert.equal((await(await fetch(base+'/api/bridge/session/'+b.token)).json()).pending,null);
  const pending=await(await fetch(base+'/api/bridge/session/'+a.token)).json();assert.equal(pending.pending.id,snap.id);
  await send('/api/bridge/session/'+a.token,{action:'ack',id:snap.id});
  assert.equal((await(await fetch(base+'/api/bridge/session/'+a.token)).json()).ack,snap.id);
  assert.equal((await send('/api/bridge/session/'+a.token,{action:'ack',id:snap.id})).status,200);
  const bound=await(await send('/api/bridge/session/'+b.token,{action:'bind',projectId:project.id})).json();assert.equal(bound.projectId,project.id);assert.equal(bound.pending,null);
  assert.equal((await send('/api/snapshots',project)).status,409);
  assert.equal((await fetch(base+'/api/projects',{method:'POST',body:'{}'})).status,403);
  assert.equal((await send('/api/bridge/sessions',{}, {'X-H3-Bridge':'1',Origin:'https://evil.example'})).status,403);
  const history=await(await fetch(base+'/api/history/'+saved.id)).json();
  assert.ok(history.some(x=>x.kind==='snapshot'&&x.key===snap.id));
  const restored=await(await send('/api/history/'+saved.id,{kind:'snapshot',key:snap.id,revision:2})).json();
  assert.deepEqual(restored.missingMentions,project.missingMentions);assert.equal(restored.prompt,project.prompt);assert.equal(restored.revision,3);
  assert.ok(restored.branchId);assert.equal(restored.parentSnapshotId,snap.id);assert.equal(restored.branchName,'Branch 3');assert.equal(restored.branchedFrom.branchId,'main');
  const restoredHistory=await(await fetch(base+'/api/history/'+saved.id)).json();assert.equal(restoredHistory.find(x=>x.kind==='current').activeBranch,true);assert.equal(restoredHistory.find(x=>x.kind==='current').restoredRevision,3);assert.equal(restoredHistory.find(x=>x.kind==='snapshot'&&x.key===snap.id).activeBranch,false);
  const branchSend=await(await send('/api/snapshots',restored)).json();assert.equal(branchSend.sendVersion,2);
  const branchDoc=JSON.parse(await readFile(branchSend.path,'utf8'));assert.equal(branchDoc.parentSnapshotId,snap.id);assert.equal(branchDoc.branchId,restored.branchId);
  const simultaneous=await Promise.all([send('/api/snapshots',restored),send('/api/snapshots',restored)]);
  assert.deepEqual((await Promise.all(simultaneous.map(x=>x.json()))).map(x=>x.sendVersion).sort(),[3,4]);
  // The project list reports the newest send version without rescanning every snapshot file each call.
  const listed=await(await fetch(base+'/api/projects')).json();
  assert.equal(listed.find(x=>x.id===saved.id).sendVersion,4);
  assert.equal((await send('/api/trash/'+saved.id,{revision:2})).status,409);
  assert.equal((await send('/api/trash/'+saved.id,{revision:3})).status,200);
  assert.equal((await fetch(base+'/api/project/'+saved.id)).status,404);
  assert.equal(JSON.parse(await readFile(snap.path,'utf8')).prompt,project.prompt);
  assert.equal((await send('/api/trash/'+saved.id,{restore:true})).status,200);
  assert.equal((await fetch(base+'/api/project/'+saved.id)).status,200);
  const prefs=await(await fetch(base+'/api/dashboard')).json();
  const trashedFolders=await(await send('/api/dashboard',{...prefs,trashFolders:['Empty folder','Parent/Child']})).json();
  assert.deepEqual(trashedFolders.trashFolders,['Empty folder','Parent/Child']);
  assert.deepEqual((await(await fetch(base+'/api/dashboard')).json()).trashFolders,trashedFolders.trashFolders);
  const latestPrefs=await(await fetch(base+'/api/dashboard')).json();
  const preferenceUpdate=await(await send('/api/dashboard',{...latestPrefs,folderCovers:{Films:project.id},inspirations:[{kind:'scene',key:project.id},{kind:'folder',key:'Films'}]})).json();
  const reread=await(await fetch(base+'/api/dashboard')).json();assert.deepEqual(reread.folderCovers,preferenceUpdate.folderCovers);assert.deepEqual(reread.inspirations,preferenceUpdate.inspirations);
  assert.equal((await send('/api/dashboard',{...reread,inspirations:[{kind:'invalid',key:'a'}]})).status,400);
  const attack={...saved,references:[{id:'../../config',type:'image'}]};
  assert.equal((await send('/api/snapshots',attack)).status,400);
});

